#! /usr/bin/env bash

level=$1

if [ "$level" == "1" ] || [ "$level" == "2" ]; then
  sleep=3
else
  sleep=10
fi

(echo -e "new $level\nmap"; sleep $sleep) | ws ws://maze.server.host/game-pipes/ 2>/dev/null | grep -v '<' > samples/$level
